name = "seatmint/ticket"
version = "0.1.0"
license = "Apache-2.0"
description = "SeatMint PoC smart contract for ticket minting and escrow on Cardano"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2"
source = "github"

[validators.ticket]
path = "validators/ticket.ak"
